name: Auto Build Action Test
"on":
  workflow_dispatch:
    inputs:
      configurables:
        description: configurables list json
        required: true
        default: N/A
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEMPLATE: service
    container:
      image: ballerina/ballerina:2201.1.1
      options: --user root
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - run: pwd
      - run: apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
      - run: which python3 
      - name: Choreo Toml Parser
        uses: choreo-templates/ballerina-toml-parser@v2
        with:
          type: read
      - name: Ballerina Build
        run: |
          bal build --sticky --export-openapi --generate-config-schema
      - name: Run Python Script
        run: python3 .github/workflows/flowsupport.py
        

      
